name: 04_dotnetpublish_00_buildRelease

on:
  push:
    branches:
      - "main"
      - "Develop"
  # push:
  #   branches:
  #     - "main"
  #     - "Develop"
  # pull_request:
  #   branches:
  #     - "main"
  workflow_call:
jobs:
  call-tests-workflow-from-build-release:
    uses: "./.github/workflows/03_dotnet_02_BuildAndRunTests.yml"
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]

    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Publish each project separately
      - name: Publish Store API
        run: dotnet publish XGO.Store/XGO.Store.Api/XGO.Store.Api.csproj --no-build --configuration Release --output ./publish/store

      - name: Publish Storage API
        run: dotnet publish XGO.Storage/XGO.Storage.Api/XGO.Storage.Api.csproj --no-build --configuration Release --output ./publish/storage

      - name: Publish Proxy API Gateway
        run: dotnet publish XGO.ApiGateway/XGO.ApiGateway.csproj --no-build --configuration Release --output ./publish/proxy

      # Upload publish result
      - name: upload store artifact
        uses: actions/upload-artifact@v4
        with:
          name: store-artifact
          overwrite: true
          path: ./publish/store
          retention-days: 1

      - name: Upload storage artifact
        uses: actions/upload-artifact@v4
        with:
          name: storage-artifact
          overwrite: true
          path: ./publish/storage
          retention-days: 1

      - name: Upload proxy artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy-artifact
          overwrite: true
          path: ./publish/proxy
          retention-days: 1
